using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using TheLastCompact.Core;

namespace TheLastCompact.Wakeup
{
    /// <summary>
    /// 第 4 阶段（4_Modern / 现代异化）总控制器。
    /// 协调鼠标点击，驱动电脑屏幕文字序列和办公室坍塌效果，并控制 2D BGM 背景音乐。
    /// 按 P 键可调试跳关到下一场景。
    /// </summary>
    public class Stage4Controller : MonoBehaviour
    {
        public static Stage4Controller Instance { get; private set; }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void AutoBootstrap()
        {
            SceneManager.sceneLoaded += OnSceneLoaded;
            if (SceneManager.GetActiveScene().name == "4_Modern")
            {
                EnsureInstance();
            }
        }

        private static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
        {
            if (scene.name == "4_Modern")
            {
                EnsureInstance();
            }
        }

        private static void EnsureInstance()
        {
            if (Instance != null) return;
#if UNITY_2023_1_OR_NEWER
            Stage4Controller existing = FindAnyObjectByType<Stage4Controller>();
#else
            Stage4Controller existing = FindObjectOfType<Stage4Controller>();
#endif
            if (existing != null) return;

            GameObject go = new GameObject("Stage4Controller_AutoGenerated");
            go.AddComponent<Stage4Controller>();
            Debug.Log("[Stage4] 自动创建 Stage4Controller。");
        }

        [Header("BGM 背景音乐与环境音")]
        [Tooltip("Stage 4 背景音乐 AudioClip（如果留空，系统会自动加载备用背景音乐）")]
        public AudioClip bgmClip;

        [Tooltip("BGM 音量 (0 ~ 1)")]
        [Range(0f, 1f)]
        public float bgmVolume = 0.45f;

        [Tooltip("办公环境白噪音 (CRT 电磁声/风扇/空调声，留空则自动程序化合成)")]
        public AudioClip officeAmbientClip;

        [Tooltip("环境白噪音音量")]
        [Range(0f, 1f)]
        public float officeAmbientVolume = 0.35f;

        [Header("打字/点击音效")]
        [Tooltip("机械键盘打字音效 (留空则自动程序化合成机械键盘敲击声)")]
        public AudioClip typingKeypressClip;

        [Tooltip("打字音效音量")]
        [Range(0f, 1f)]
        public float typingSoundVolume = 0.75f;

        [Header("子系统引用（若为空则自动查找）")]
        public MonitorTextController monitorText;
        public OfficeCollapseController officeCollapse;

        [Header("环境初始化")]
        [Tooltip("启动时自动将环境光设为黑色，让 Spotlight 效果更突出")]
        public bool darkenAmbientOnStart = true;

        [Tooltip("启动时是否清理隐藏所有 2D UI 界面（确保只在 3D 屏幕上显示文案）")]
        public bool clean2DHUDOverlays = true;

        [Header("转场参数")]
        public float transitionDelay = 2f;
        public string nextSceneName = "5_Contemporary_1";

        private AudioSource _bgmAudioSource;
        private AudioSource _ambientAudioSource;
        private AudioSource _sfxAudioSource;
        private bool _isTransitioning = false;
        private int _totalClicks = 0;

        private void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(gameObject); return; }
            Instance = this;

            _sfxAudioSource = gameObject.AddComponent<AudioSource>();
            _sfxAudioSource.spatialBlend = 0f;
        }

        private void Start()
        {
            // 自动配置 BGM 与办公环境白噪音
            SetupBGMAndAmbient();

            // 清理 2D UI 弹窗与计数器，保证界面 100% 干净
            if (clean2DHUDOverlays)
            {
                Clean2DHUDOverlays();
            }

            // 自动绑定子系统
#if UNITY_2023_1_OR_NEWER
            if (monitorText == null) monitorText = FindAnyObjectByType<MonitorTextController>();
            if (officeCollapse == null) officeCollapse = FindAnyObjectByType<OfficeCollapseController>();
#else
            if (monitorText == null) monitorText = FindObjectOfType<MonitorTextController>();
            if (officeCollapse == null) officeCollapse = FindObjectOfType<OfficeCollapseController>();
#endif

            // 压暗环境光
            if (darkenAmbientOnStart)
            {
                RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
                RenderSettings.ambientLight = Color.black;
                Debug.Log("[Stage4] 环境光已设为黑色，舞台准备就绪。");
            }

            // 自动装配 Stage 4 走出去切关控制器
            if (Stage4WalkOutExitController.Instance == null && GetComponent<Stage4WalkOutExitController>() == null)
            {
                gameObject.AddComponent<Stage4WalkOutExitController>();
            }

            // 强行激活玩家控制（允许 WASD 移动与视角旋转）
            UniversalPlayer player = FindObjectOfType<UniversalPlayer>();
            if (player != null)
            {
                player.EnableControl();
            }

            if (GlobalUIManager.Instance != null)
            {
                GlobalUIManager.Instance.isGameplayActive = true;
            }

            Debug.Log("[Stage4] 关卡初始化完成，玩家控制已激活。点击鼠标左键开始工作...");
        }

        private void Clean2DHUDOverlays()
        {
            // 1. 隐藏场景中所有的 WorkCounterUI 计数器
            WorkCounterUI[] counters = FindObjectsOfType<WorkCounterUI>(true);
            foreach (var c in counters)
            {
                c.gameObject.SetActive(false);
            }

            // 2. 隐藏场景中残存的悬浮大字（如 "You don't have to decide anything..."）
            TMPro.TMP_Text[] allTmpText = FindObjectsOfType<TMPro.TMP_Text>(true);
            foreach (var tmp in allTmpText)
            {
                if (tmp.transform.parent != null && tmp.transform.parent.name == "MonitorCanvas") continue;
                if (tmp.text.Contains("You don't have to decide") || tmp.gameObject.name == "Text (TMP)")
                {
                    tmp.gameObject.SetActive(false);
                }
            }
        }

        private void SetupBGMAndAmbient()
        {
            // 关掉之前残留的对话旁白系统 NarratorManager
            if (NarratorManager.Instance != null)
            {
                NarratorManager.Instance.StopCurrent();
                NarratorManager.Instance.gameObject.SetActive(false);
            }

            // BGM
            _bgmAudioSource = gameObject.AddComponent<AudioSource>();
            _bgmAudioSource.loop = true;
            _bgmAudioSource.volume = bgmVolume;
            _bgmAudioSource.spatialBlend = 0f;

            if (bgmClip != null)
            {
                _bgmAudioSource.clip = bgmClip;
                _bgmAudioSource.Play();
            }

            // 环境白噪音 AudioSource
            _ambientAudioSource = gameObject.AddComponent<AudioSource>();
            _ambientAudioSource.loop = true;
            _ambientAudioSource.volume = officeAmbientVolume;
            _ambientAudioSource.spatialBlend = 0f;

            if (officeAmbientClip != null)
            {
                _ambientAudioSource.clip = officeAmbientClip;
                _ambientAudioSource.Play();
            }
            else
            {
                _ambientAudioSource.clip = CreateSynthOfficeAmbientClip();
                _ambientAudioSource.Play();
            }
        }

        private void Update()
        {
            // 鼠标左键点击交互
            if (Input.GetMouseButtonDown(0))
            {
                OnPlayerClick();
            }

            // P 键调试跳关
            if (Input.GetKeyDown(KeyCode.P) && !_isTransitioning)
            {
                StartCoroutine(TransitionSequence());
            }
        }

        private void OnPlayerClick()
        {
            _totalClicks++;

            // 播放机械打字/敲击音效
            PlayTypingKeypressSound();

            // 驱动电脑屏幕文字更新
            monitorText?.OnClick();

            // 驱动所有 Office 向内坍塌
            officeCollapse?.OnClick();

            // 驱动 Stage4WalkOutExitController 坍塌计数
            if (Stage4WalkOutExitController.Instance != null)
                Stage4WalkOutExitController.Instance.OnWorkClick();

            // 记录行为数据
            if (PlayerBehaviorData.Instance != null)
                PlayerBehaviorData.Instance.AddWork();

            Debug.Log($"[Stage4] 点击次数: {_totalClicks}");
        }

        private void PlayTypingKeypressSound()
        {
            if (typingKeypressClip != null)
            {
                _sfxAudioSource.pitch = Random.Range(0.92f, 1.08f);
                _sfxAudioSource.PlayOneShot(typingKeypressClip, typingSoundVolume);
                _sfxAudioSource.pitch = 1.0f;
            }
            else
            {
                // 程序化合成机械键盘敲击音效
                _sfxAudioSource.pitch = Random.Range(0.88f, 1.12f);
                _sfxAudioSource.PlayOneShot(CreateSynthTypingClickClip(), typingSoundVolume * 0.7f);
                _sfxAudioSource.pitch = 1.0f;
            }
        }

        // ─────────────────────────────────────────────────────────────────
        // Procedural Audio Synthesis Fallbacks (白噪音与打字声程序化合成)

        private static AudioClip _cachedAmbientClip;
        private static AudioClip _cachedTypingClip;

        private AudioClip CreateSynthOfficeAmbientClip()
        {
            if (_cachedAmbientClip != null) return _cachedAmbientClip;

            int sampleRate = 44100;
            float duration = 2.0f;
            int samples = (int)(sampleRate * duration);
            float[] data = new float[samples];

            for (int i = 0; i < samples; i++)
            {
                // 低频 CRT 蜂鸣 + 空调白噪音
                float whiteNoise = (Random.value * 2f - 1f) * 0.08f;
                float hum = Mathf.Sin(2f * Mathf.PI * 60f * i / sampleRate) * 0.04f;
                data[i] = whiteNoise + hum;
            }

            _cachedAmbientClip = AudioClip.Create("SynthOfficeAmbient", samples, 1, sampleRate, false);
            _cachedAmbientClip.SetData(data, 0);
            return _cachedAmbientClip;
        }

        private AudioClip CreateSynthTypingClickClip()
        {
            if (_cachedTypingClip != null) return _cachedTypingClip;

            int sampleRate = 44100;
            float duration = 0.06f;
            int samples = (int)(sampleRate * duration);
            float[] data = new float[samples];

            for (int i = 0; i < samples; i++)
            {
                float t = (float)i / samples;
                float env = Mathf.Exp(-t * 25f);
                float noise = (Random.value * 2f - 1f) * env;
                float clickPeak = Mathf.Sin(2f * Mathf.PI * 1800f * i / sampleRate) * env * 0.8f;
                data[i] = (noise + clickPeak) * 0.5f;
            }

            _cachedTypingClip = AudioClip.Create("SynthTypingClick", samples, 1, sampleRate, false);
            _cachedTypingClip.SetData(data, 0);
            return _cachedTypingClip;
        }

        public void TriggerSceneComplete()
        {
            if (_isTransitioning) return;
            StartCoroutine(TransitionSequence());
        }

        private IEnumerator TransitionSequence()
        {
            _isTransitioning = true;
            EventBus.RaiseAnnouncement("The walls are closing in. But the work goes on.");
            yield return new WaitForSeconds(transitionDelay);
            PerformSceneTransition();
        }

        private void PerformSceneTransition()
        {
            EventBus.RaiseSceneComplete();
#if UNITY_EDITOR
            if (FindAnyObjectByType<SceneTransitionManager>() == null)
            {
                string targetScene = (string.IsNullOrEmpty(nextSceneName) || nextSceneName == "5_Contemporary")
                    ? "5_Contemporary_1"
                    : nextSceneName;

                Debug.LogWarning($"[Stage4Controller] 单关测试模式：直接加载 {targetScene}");
                SceneManager.LoadScene(targetScene);
            }
#endif
        }
    }
}
