using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using TheLastCompact.Core;

namespace TheLastCompact.Wakeup
{
    /// <summary>
    /// 第 4 阶段（4_Modern / 现代异化）总控制器。
    /// 协调鼠标点击，驱动电脑屏幕文字序列和办公室坍塌效果，并控制 2D BGM 背景音乐。
    /// 按 P 键可调试跳关到下一场景。
    /// </summary>
    public class Stage4Controller : MonoBehaviour
    {
        public static Stage4Controller Instance { get; private set; }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void AutoBootstrap()
        {
            SceneManager.sceneLoaded += OnSceneLoaded;
            if (SceneManager.GetActiveScene().name == "4_Modern")
            {
                EnsureInstance();
            }
        }

        private static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
        {
            if (scene.name == "4_Modern")
            {
                EnsureInstance();
            }
        }

        private static void EnsureInstance()
        {
            if (Instance != null) return;
#if UNITY_2023_1_OR_NEWER
            Stage4Controller existing = FindAnyObjectByType<Stage4Controller>();
#else
            Stage4Controller existing = FindObjectOfType<Stage4Controller>();
#endif
            if (existing != null) return;

            GameObject go = new GameObject("Stage4Controller_AutoGenerated");
            go.AddComponent<Stage4Controller>();
            Debug.Log("[Stage4] 自动创建 Stage4Controller。");
        }

        [Header("BGM 背景音乐")]
        [Tooltip("Stage 4 背景音乐 AudioClip（如果留空，系统会自动加载备用背景音乐）")]
        public AudioClip bgmClip;

        [Tooltip("BGM 音量 (0 ~ 1)")]
        [Range(0f, 1f)]
        public float bgmVolume = 0.5f;

        [Tooltip("是否循环播放 BGM")]
        public bool loopBgm = true;

        [Header("子系统引用（若为空则自动查找）")]
        public MonitorTextController monitorText;
        public OfficeCollapseController officeCollapse;

        [Header("环境初始化")]
        [Tooltip("启动时自动将环境光设为黑色，让 Spotlight 效果更突出")]
        public bool darkenAmbientOnStart = true;

        [Header("转场参数")]
        public float transitionDelay = 2f;
        public string nextSceneName = "5_Contemporary_1";

        private AudioSource _bgmAudioSource;
        private bool _isTransitioning = false;
        private int _totalClicks = 0;

        private void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(gameObject); return; }
            Instance = this;
        }

        private void Start()
        {
            // 自动配置 BGM
            SetupBGM();

            // 自动绑定子系统
#if UNITY_2023_1_OR_NEWER
            if (monitorText == null) monitorText = FindAnyObjectByType<MonitorTextController>();
            if (officeCollapse == null) officeCollapse = FindAnyObjectByType<OfficeCollapseController>();
#else
            if (monitorText == null) monitorText = FindObjectOfType<MonitorTextController>();
            if (officeCollapse == null) officeCollapse = FindObjectOfType<OfficeCollapseController>();
#endif

            // 压暗环境光
            if (darkenAmbientOnStart)
            {
                RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
                RenderSettings.ambientLight = Color.black;
                Debug.Log("[Stage4] 环境光已设为黑色，舞台准备就绪。");
            }

            // 自动装配 Stage 4 走出去切关控制器
            if (Stage4WalkOutExitController.Instance == null && GetComponent<Stage4WalkOutExitController>() == null)
            {
                gameObject.AddComponent<Stage4WalkOutExitController>();
            }

            Debug.Log("[Stage4] 关卡初始化完成。点击鼠标左键开始工作...");
        }

        private void SetupBGM()
        {
            // 关掉之前残留的对话旁白系统 NarratorManager
            if (NarratorManager.Instance != null)
            {
                NarratorManager.Instance.StopCurrent();
                NarratorManager.Instance.gameObject.SetActive(false);
            }

            _bgmAudioSource = gameObject.AddComponent<AudioSource>();
            _bgmAudioSource.loop = loopBgm;
            _bgmAudioSource.volume = bgmVolume;
            _bgmAudioSource.spatialBlend = 0f;

            if (bgmClip != null)
            {
                _bgmAudioSource.clip = bgmClip;
                _bgmAudioSource.Play();
                Debug.Log($"[Stage4] 播放指定的 BGM: {bgmClip.name}");
            }
        }

        private void Update()
        {
            // 鼠标左键点击交互
            if (Input.GetMouseButtonDown(0))
            {
                OnPlayerClick();
            }

            // P 键调试跳关
            if (Input.GetKeyDown(KeyCode.P) && !_isTransitioning)
            {
                StartCoroutine(TransitionSequence());
            }
        }

        private void OnPlayerClick()
        {
            _totalClicks++;

            // 驱动电脑屏幕文字更新
            monitorText?.OnClick();

            // 驱动所有 Office 向内坍塌
            officeCollapse?.OnClick();

            // 驱动 Stage4WalkOutExitController 坍塌计数
            if (Stage4WalkOutExitController.Instance != null)
                Stage4WalkOutExitController.Instance.OnWorkClick();

            // 记录行为数据
            if (PlayerBehaviorData.Instance != null)
                PlayerBehaviorData.Instance.AddWork();

            Debug.Log($"[Stage4] 点击次数: {_totalClicks}");
        }

        public void TriggerSceneComplete()
        {
            if (_isTransitioning) return;
            StartCoroutine(TransitionSequence());
        }

        private IEnumerator TransitionSequence()
        {
            _isTransitioning = true;
            EventBus.RaiseAnnouncement("The walls are closing in. But the work goes on.");
            yield return new WaitForSeconds(transitionDelay);
            PerformSceneTransition();
        }

        private void PerformSceneTransition()
        {
            EventBus.RaiseSceneComplete();
#if UNITY_EDITOR
            if (FindAnyObjectByType<SceneTransitionManager>() == null)
            {
                Debug.LogWarning($"[Stage4Controller] 单关测试模式：直接加载 {nextSceneName}");
                SceneManager.LoadScene(nextSceneName);
            }
#endif
        }
    }
}
