using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using TheLastCompact.Core;

namespace TheLastCompact.Wakeup
{
    /// <summary>
    /// 第 3 阶段（3_Rock / 莫比乌斯西西弗斯）总控制器
    /// 包含：BGM 背景音乐自动挂载、关卡跳转控制、按 P 键调试跳关。
    /// </summary>
    public class Stage3Controller : MonoBehaviour
    {
        public static Stage3Controller Instance { get; private set; }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void AutoBootstrap()
        {
            SceneManager.sceneLoaded += OnSceneLoaded;
            string sceneName = SceneManager.GetActiveScene().name;
            if (sceneName == "3_Rock" || sceneName == "3_Rock_2")
            {
                EnsureInstance();
            }
        }

        private static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
        {
            if (scene.name == "3_Rock" || scene.name == "3_Rock_2")
            {
                EnsureInstance();
            }
        }

        private static void EnsureInstance()
        {
            if (Instance != null) return;
#if UNITY_2023_1_OR_NEWER
            Stage3Controller existing = FindAnyObjectByType<Stage3Controller>();
#else
            Stage3Controller existing = FindObjectOfType<Stage3Controller>();
#endif
            if (existing != null) return;

            GameObject go = new GameObject("Stage3Controller_AutoGenerated");
            go.AddComponent<Stage3Controller>();
            Debug.Log("[Stage3] 自动创建 Stage3Controller。");
        }

        [Header("BGM 背景音乐")]
        [Tooltip("Stage 3 背景音乐 AudioClip（如果留空，系统会自动配对加载备用音轨）")]
        public AudioClip bgmClip;

        [Tooltip("BGM 音量 (0 ~ 1)")]
        [Range(0f, 1f)]
        public float bgmVolume = 0.5f;

        [Tooltip("是否循环播放 BGM")]
        public bool loopBgm = true;

        [Header("转场参数")]
        [Tooltip("转场前的等待时间（秒），用于播放声效/淡出动画")]
        public float transitionDelay = 1.5f;

        [Tooltip("下一关场景名称，在没有 SceneTransitionManager 的单关测试模式中使用")]
        public string nextSceneName = "4_Modern";

        private AudioSource _bgmAudioSource;
        private bool _isTransitioning = false;

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }
            Instance = this;
        }

        private void Start()
        {
            SetupBGM();
            EnsureLoopBreakInteractable();
        }

        private void EnsureLoopBreakInteractable()
        {
            if (FindObjectOfType<Stage3LoopBreakInteractable>() != null) return;

            // 寻找山顶或巨石作为生成位置
            Vector3 spawnPos = new Vector3(0f, 6f, 15f);
            SisyphusRock rock = FindObjectOfType<SisyphusRock>();
            if (rock != null)
            {
                if (rock.topOfSlope != null)
                {
                    spawnPos = rock.topOfSlope.position;
                }
                else
                {
                    spawnPos = rock.transform.position + Vector3.up * 2f + Vector3.forward * 8f;
                }
            }

            GameObject breakGo = new GameObject("Stage3_LoopBreakInteractable");
            breakGo.transform.position = spawnPos;
            breakGo.AddComponent<Stage3LoopBreakInteractable>();
            Debug.Log($"[Stage3] 自动为场景在 {spawnPos} 处生成了 '放弃推动 (踏出循环)' 缝合线交互点！");
        }

        private void SetupBGM()
        {
            // 关掉之前残留的对话旁白系统 NarratorManager
            if (NarratorManager.Instance != null)
            {
                NarratorManager.Instance.StopCurrent();
                NarratorManager.Instance.gameObject.SetActive(false);
            }

            _bgmAudioSource = gameObject.AddComponent<AudioSource>();
            _bgmAudioSource.loop = loopBgm;
            _bgmAudioSource.volume = bgmVolume;
            _bgmAudioSource.spatialBlend = 0f;

            if (bgmClip != null)
            {
                _bgmAudioSource.clip = bgmClip;
                _bgmAudioSource.Play();
                Debug.Log($"[Stage3] 播放指定的 BGM: {bgmClip.name}");
            }
        }

        private void Update()
        {
            // 调试快捷键：按 P 键直接触发转场（测试阶段用）
            if (Input.GetKeyDown(KeyCode.P) && !_isTransitioning)
            {
                Debug.Log("[Stage3] 按下 P 键，触发转场跳过至下一关...");
                StartCoroutine(TransitionSequence());
            }
        }

        /// <summary>
        /// 公共接口：供大门交互、山顶石门、叙事脚本等调用以触发转场
        /// </summary>
        public void TriggerSceneComplete()
        {
            if (_isTransitioning) return;
            StartCoroutine(TransitionSequence());
        }

        private IEnumerator TransitionSequence()
        {
            _isTransitioning = true;
            EventBus.RaiseAnnouncement("The loop has no end. But you can still walk away.");
            yield return new WaitForSeconds(transitionDelay);
            PerformSceneTransition();
        }

        private void PerformSceneTransition()
        {
            EventBus.RaiseSceneComplete();

#if UNITY_EDITOR
            if (FindAnyObjectByType<SceneTransitionManager>() == null)
            {
                Debug.LogWarning($"[Stage3Controller] 未检测到 SceneTransitionManager，单关测试模式：直接加载 {nextSceneName}");
                SceneManager.LoadScene(nextSceneName);
            }
#endif
        }
    }
}
