using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using TheLastCompact.Core;

namespace TheLastCompact.Wakeup
{
    /// <summary>
    /// Stage 5 总控制器 — "Feed / 内容流"
    /// 
    /// 一套系统，四个阶段。用单个 phaseProgress (0→1) 驱动无缝进化：
    /// Phase 1 (0.00~0.35): 多彩的享受 (Sensory Liberation & Delights)
    /// Phase 2 (0.35~0.70): 不自觉的强迫成瘾机械行为 (Compulsive Algorithmic Addiction)
    /// Phase 3 (0.70~0.96): 数据显形，无处遁形的宿命 (Data Exposed: Inescapable Destiny)
    /// Phase 4 (0.96~1.00): 抉择时刻 (Moment of Choice: Stay Here or Challenge Stage 6)
    /// </summary>
    public class Stage5Controller : MonoBehaviour
    {
        public static Stage5Controller Instance { get; private set; }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void AutoBootstrap()
        {
            SceneManager.sceneLoaded += OnSceneLoaded;
            if (SceneManager.GetActiveScene().name == "5_Contemporary")
            {
                EnsureInstance();
            }
        }

        private static void OnSceneLoaded(UnityEngine.SceneManagement.Scene scene, LoadSceneMode mode)
        {
            if (scene.name == "5_Contemporary")
            {
                EnsureInstance();
            }
        }

        private static void EnsureInstance()
        {
            if (Instance != null) return;
#if UNITY_2023_1_OR_NEWER
            Stage5Controller existing = FindAnyObjectByType<Stage5Controller>();
#else
            Stage5Controller existing = FindObjectOfType<Stage5Controller>();
#endif
            if (existing != null) return;

            GameObject go = new GameObject("Stage5Controller_AutoGenerated");
            go.AddComponent<Stage5Controller>();
            Debug.Log("[Stage5] 自动创建 Stage5Controller。");
        }

        [Header("Phase 进度（放慢 30%）")]
        [Tooltip("当前阶段进度 0→1，Inspector 中可观测")]
        [Range(0f, 1f)]
        public float phaseProgress = 0f;

        [Tooltip("每次注视交互推进的增量（放慢 30%）")]
        public float progressPerGaze = 0.035f;

        [Tooltip("时间自动推进速率（每秒，放慢 30%）")]
        public float progressPerSecond = 0.0105f;

        [Header("注视检测")]
        [Tooltip("注视射线的最大检测距离")]
        public float gazeRayDistance = 50f;

        [Tooltip("持续注视多久算一次交互（秒）")]
        public float gazeHoldTime = 0.3f;

        [Header("声音控制")]
        [Tooltip("Phase C 私密数据出现时，全局音量降到此值")]
        public float silenceVolume = 0.05f;

        [Header("转场")]
        public float transitionDelay = 2f;
        public string nextSceneName = "6_Future";

        // 子系统引用
        private ContentCardSpawner _spawner;
        private FeedEnvironment _environment;

        // 注视状态
        private ContentCard _currentGazedCard = null;
        private float _gazeTimer = 0f;
        private bool _gazeTriggered = false;

        // 结尾选择
        private bool _endChoiceSpawned = false;
        private bool _isTransitioning = false;

        // 音量与 HUD
        private float _originalVolume = 1f;
        private float _targetVolume = 1f;
        private TMPro.TextMeshProUGUI _phaseStatusText;

        private void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(gameObject); return; }
            Instance = this;
        }

        private void Start()
        {
            // 0. 确保场景原有的 UI Canvas 保持显示
            EnsureOldCanvasesVisible();

            // 1. 压暗环境
            RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
            RenderSettings.ambientLight = Color.black;
            RenderSettings.skybox = null;

            Camera mainCam = GetMainCamera();
            if (mainCam != null)
            {
                mainCam.clearFlags = CameraClearFlags.SolidColor;
                mainCam.backgroundColor = Color.black;
            }

            // 2. 设置玩家视角只可旋转、移速归零
            SetupPlayerFloat();

            // 3. 创建注视准心与 Phase 阶段状态提示 HUD
            CreateHUDUI();

            // 4. 创建子系统
            CreateSubsystems();

            // 5. 保存原始音量
            _originalVolume = AudioListener.volume;

            Debug.Log("[Stage5] Feed 系统已初始化。Phase 1 开始。");
        }

        private void EnsureOldCanvasesVisible()
        {
            UnityEngine.Canvas[] canvases = FindObjectsOfType<UnityEngine.Canvas>();
            foreach (var c in canvases)
            {
                c.gameObject.SetActive(true);
            }
        }

        private void CreateHUDUI()
        {
            GameObject canvasGo = new GameObject("HUDCanvas");
            UnityEngine.Canvas canvas = canvasGo.AddComponent<UnityEngine.Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvas.sortingOrder = 100;
            canvasGo.AddComponent<UnityEngine.UI.CanvasScaler>();

            // 屏幕中央准心小白点
            GameObject dotGo = new GameObject("ReticleDot");
            dotGo.transform.SetParent(canvasGo.transform, false);
            UnityEngine.UI.Image img = dotGo.AddComponent<UnityEngine.UI.Image>();
            img.color = new Color(1f, 1f, 1f, 0.6f);

            RectTransform rtDot = dotGo.GetComponent<RectTransform>();
            rtDot.sizeDelta = new Vector2(6f, 6f);
            rtDot.anchoredPosition = Vector2.zero;

            // 顶部 Phase 阶段状态栏背景面板
            GameObject bannerBgGo = new GameObject("PhaseBannerPanel");
            bannerBgGo.transform.SetParent(canvasGo.transform, false);
            UnityEngine.UI.Image bgImg = bannerBgGo.AddComponent<UnityEngine.UI.Image>();
            bgImg.color = new Color(0.05f, 0.07f, 0.12f, 0.88f);

            RectTransform rtBg = bannerBgGo.GetComponent<RectTransform>();
            rtBg.anchorMin = new Vector2(0.5f, 1f);
            rtBg.anchorMax = new Vector2(0.5f, 1f);
            rtBg.pivot = new Vector2(0.5f, 1f);
            rtBg.anchoredPosition = new Vector2(0f, -18f);
            rtBg.sizeDelta = new Vector2(620f, 46f);

            // Phase 阶段文字
            GameObject textGo = new GameObject("PhaseStatusText");
            textGo.transform.SetParent(bannerBgGo.transform, false);
            _phaseStatusText = textGo.AddComponent<TMPro.TextMeshProUGUI>();
            _phaseStatusText.fontSize = 20f;
            _phaseStatusText.alignment = TMPro.TextAlignmentOptions.Center;
            _phaseStatusText.fontStyle = TMPro.FontStyles.Bold;

            RectTransform rtText = textGo.GetComponent<RectTransform>();
            rtText.anchorMin = Vector2.zero;
            rtText.anchorMax = Vector2.one;
            rtText.sizeDelta = Vector2.zero;
            rtText.anchoredPosition = Vector2.zero;
        }

        private void UpdatePhaseHUD()
        {
            if (_phaseStatusText == null) return;

            if (phaseProgress < 0.35f)
            {
                _phaseStatusText.text = "<color=#00FFCC>PHASE 1</color>  —  Sensory Liberation & Delights";
            }
            else if (phaseProgress < 0.70f)
            {
                _phaseStatusText.text = "<color=#FFCC00>PHASE 2</color>  —  Compulsive Algorithmic Addiction";
            }
            else if (phaseProgress < 0.96f)
            {
                _phaseStatusText.text = "<color=#FF3366>PHASE 3</color>  —  Data Exposed: Inescapable Destiny";
            }
            else
            {
                _phaseStatusText.text = "<color=#AA55FF>PHASE 4</color>  —  Moment of Choice: Stay Here or Challenge Stage 6";
            }
        }

        private Camera GetMainCamera()
        {
            Camera cam = Camera.main;
            if (cam == null)
            {
#if UNITY_2023_1_OR_NEWER
                cam = FindAnyObjectByType<Camera>();
#else
                cam = FindObjectOfType<Camera>();
#endif
            }
            return cam;
        }

        private void SetupPlayerFloat()
        {
#if UNITY_2023_1_OR_NEWER
            UniversalPlayer player = FindAnyObjectByType<UniversalPlayer>();
#else
            UniversalPlayer player = FindObjectOfType<UniversalPlayer>();
#endif
            if (player != null)
            {
                player.moveSpeed = 0f;
                player.EnableControl();
                Debug.Log("[Stage5] 玩家移速已设为 0，视角旋转已启用。");
            }

            CursorService.Lock();
        }

        private void Update()
        {
            // 快捷键调试：按数字键 1~5 直接切到对应 Phase
            if (Input.GetKeyDown(KeyCode.Alpha1) || Input.GetKeyDown(KeyCode.Keypad1))
            {
                phaseProgress = 0.05f;
                if (_spawner != null) _spawner.enabled = true;
                Debug.Log("<color=green>[Stage5 调试] 跳转至 Phase 1 (Sensory Liberation)</color>");
            }
            else if (Input.GetKeyDown(KeyCode.Alpha2) || Input.GetKeyDown(KeyCode.Keypad2))
            {
                phaseProgress = 0.40f;
                if (_spawner != null) _spawner.enabled = true;
                Debug.Log("<color=yellow>[Stage5 调试] 跳转至 Phase 2 (Compulsive Addiction)</color>");
            }
            else if (Input.GetKeyDown(KeyCode.Alpha3) || Input.GetKeyDown(KeyCode.Keypad3))
            {
                phaseProgress = 0.75f;
                if (_spawner != null) _spawner.enabled = true;
                Debug.Log("<color=orange>[Stage5 调试] 跳转至 Phase 3 (Data Exposed)</color>");
            }
            else if (Input.GetKeyDown(KeyCode.Alpha4) || Input.GetKeyDown(KeyCode.Keypad4))
            {
                phaseProgress = 0.92f;
                if (_spawner != null) _spawner.enabled = true;
                Debug.Log("<color=red>[Stage5 调试] 跳转至 Phase 3 (Private Data Nuclear Log)</color>");
            }
            else if (Input.GetKeyDown(KeyCode.Alpha5) || Input.GetKeyDown(KeyCode.Keypad5))
            {
                phaseProgress = 0.98f;
                Debug.Log("<color=cyan>[Stage5 调试] 跳转至 Phase 4 (Moment of Choice)</color>");
            }

            // 自动推进 phaseProgress
            if (phaseProgress < 1f)
            {
                phaseProgress += progressPerSecond * Time.deltaTime;
                phaseProgress = Mathf.Clamp01(phaseProgress);
            }

            // 同步旋钮给子系统
            if (_spawner != null) _spawner.phaseProgress = phaseProgress;
            if (_environment != null) _environment.phaseProgress = phaseProgress;

            // 动态更新顶部 Phase 阶段状态栏 HUD
            UpdatePhaseHUD();

            // 注视射线检测
            ProcessGaze();

            // 音量平滑过渡
            AudioListener.volume = Mathf.Lerp(AudioListener.volume, _targetVolume, Time.deltaTime * 3f);

            // Phase 4 结尾选择
            if (phaseProgress >= 0.96f && !_endChoiceSpawned)
            {
                SpawnEndChoice();
            }

            // P 键调试跳关
            if (Input.GetKeyDown(KeyCode.P) && !_isTransitioning)
            {
                StartCoroutine(TransitionSequence());
            }
        }

        private void CreateSubsystems()
        {
            GameObject spawnerGo = new GameObject("ContentCardSpawner");
            spawnerGo.transform.SetParent(transform, false);
            _spawner = spawnerGo.AddComponent<ContentCardSpawner>();
            _spawner.OnCardSpawned += OnCardSpawned;

            GameObject envGo = new GameObject("FeedEnvironment");
            envGo.transform.SetParent(transform, false);
            _environment = envGo.AddComponent<FeedEnvironment>();
        }

        private void OnCardSpawned(ContentCard card)
        {
            card.OnChoiceSelected += OnChoiceSelected;
        }

        private void ProcessGaze()
        {
            Camera cam = Camera.main;
            if (cam == null) return;

            Ray ray = new Ray(cam.transform.position, cam.transform.forward);
            RaycastHit hit;

            if (Physics.Raycast(ray, out hit, gazeRayDistance))
            {
                ContentCard card = hit.collider.GetComponentInParent<ContentCard>();
                if (card != null)
                {
                    if (_currentGazedCard != card)
                    {
                        if (_currentGazedCard != null) _currentGazedCard.OnGazeExit();
                        _currentGazedCard = card;
                        _gazeTimer = 0f;
                        _gazeTriggered = false;
                    }

                    _gazeTimer += Time.deltaTime;

                    // 如果是选择卡，降低注视响应所需时间（0.15s 秒触）
                    float requiredGazeTime = card.isChoiceCard ? 0.15f : gazeHoldTime;

                    if (_gazeTimer >= requiredGazeTime && !_gazeTriggered)
                    {
                        _gazeTriggered = true;
                        card.OnGazeEnter();

                        phaseProgress += progressPerGaze;
                        phaseProgress = Mathf.Clamp01(phaseProgress);

                        if (card.isPrivateDataCard)
                        {
                            _targetVolume = silenceVolume;
                        }
                        else
                        {
                            _targetVolume = _originalVolume;
                        }

                        LogPhase();
                    }

                    return;
                }
            }

            if (_currentGazedCard != null)
            {
                _currentGazedCard.OnGazeExit();
                _currentGazedCard = null;
                _gazeTimer = 0f;
                _gazeTriggered = false;
            }

            _targetVolume = _originalVolume;
        }

        /// <summary>
        /// 生成 Phase 4 抉择时刻卡片（自动清理场上所有普通卡片并暂停生成器，呈现无遮挡的清爽场景）
        /// </summary>
        private void SpawnEndChoice()
        {
            _endChoiceSpawned = true;
            Debug.Log("[Stage5] 进入 Phase 4 抉择时刻：暂停卡片推送，清理干扰卡片。");

            // 1. 暂停生成器
            if (_spawner != null) _spawner.enabled = false;

            // 2. 清理场上所有普通 Feed 卡片
            ContentCard[] activeCards = FindObjectsOfType<ContentCard>();
            foreach (var c in activeCards)
            {
                if (!c.isChoiceCard) Destroy(c.gameObject);
            }

            Camera cam = Camera.main;
            if (cam == null) return;
            Vector3 fwd = cam.transform.forward;
            Vector3 right = cam.transform.right;

            // 3. 在眼前无遮挡位置生成两张清爽比例合适的选择卡片
            SpawnChoiceCard(
                cam.transform.position + fwd * 6.0f - right * 1.6f,
                "[ INFINITE LOOP ]",
                "",
                "STAY HERE\nKeep Scrolling",
                "stay",
                new Color(0.2f, 0.6f, 0.95f, 0.95f)
            );

            SpawnChoiceCard(
                cam.transform.position + fwd * 6.0f + right * 1.6f,
                "[ BREAK THE LOOP ]",
                "",
                "FACE THE FUTURE\nChallenge Stage 6",
                "continue",
                new Color(1f, 0.55f, 0.15f, 0.95f)
            );
        }

        private void SpawnChoiceCard(Vector3 pos, string tag, string icon, string headline, string action, Color color)
        {
            GameObject cardGo = GameObject.CreatePrimitive(PrimitiveType.Quad);
            cardGo.name = $"ChoiceCard_{action}";
            cardGo.transform.position = pos;
            cardGo.transform.localScale = new Vector3(2.2f, 2.8f, 1f);

            Collider col = cardGo.GetComponent<Collider>();
            if (col != null) Destroy(col);
            BoxCollider box = cardGo.AddComponent<BoxCollider>();
            box.isTrigger = true;

            Shader shader = Shader.Find("Universal Render Pipeline/Unlit");
            if (shader == null) shader = Shader.Find("Sprites/Default");
            if (shader == null) shader = Shader.Find("Unlit/Color");
            Renderer rend = cardGo.GetComponent<Renderer>();
            Material mat = new Material(shader);
            if (mat.HasProperty("_Surface")) mat.SetFloat("_Surface", 1);
            if (mat.HasProperty("_SrcBlend")) mat.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha);
            if (mat.HasProperty("_DstBlend")) mat.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
            if (mat.HasProperty("_ZWrite")) mat.SetInt("_ZWrite", 0);
            mat.renderQueue = 3000;
            rend.material = mat;

            ContentCard card = cardGo.AddComponent<ContentCard>();
            card.categoryTag = tag;
            card.cardIcon = icon;
            card.cardHeadline = headline;
            card.cardColor = color;
            card.isChoiceCard = true;
            card.choiceAction = action;
            card.driftSpeed = 0.05f;
            card.gazeAttractSpeed = 1.2f;
            card.maxLifetime = 9999f;
            card.OnChoiceSelected += OnChoiceSelected;
        }

        private void OnChoiceSelected(string action)
        {
            if (_isTransitioning) return;

            if (action == "continue")
            {
                Debug.Log("[Stage5] 玩家选择踏入前方：挑战 Stage 6！");
                StartCoroutine(TransitionSequence());
            }
            else if (action == "stay")
            {
                Debug.Log("[Stage5] 玩家选择留在此地：重置 Feed 循环并重新恢复推送。");
                ContentCard[] cards = FindObjectsOfType<ContentCard>();
                foreach (var c in cards)
                {
                    if (c.isChoiceCard) Destroy(c.gameObject);
                }

                // 重新启用生成器
                if (_spawner != null) _spawner.enabled = true;

                phaseProgress = 0.05f;
                _endChoiceSpawned = false;
            }
        }

        private IEnumerator TransitionSequence()
        {
            _isTransitioning = true;
            EventBus.RaiseAnnouncement("The feed never ends. But you chose to look away and face the future.");
            yield return new WaitForSeconds(transitionDelay);
            PerformSceneTransition();
        }

        private void PerformSceneTransition()
        {
            AudioListener.volume = _originalVolume;
            EventBus.RaiseSceneComplete();

#if UNITY_EDITOR
            if (FindAnyObjectByType<SceneTransitionManager>() == null)
            {
                Debug.LogWarning($"[Stage5] 未检测到 SceneTransitionManager，单关测试模式：直接加载 {nextSceneName}");
                SceneManager.LoadScene(nextSceneName);
            }
#endif
        }

        private void LogPhase()
        {
            string phase = phaseProgress < 0.35f ? "1 (Sensory Liberation)"
                         : phaseProgress < 0.70f ? "2 (Compulsive Addiction)"
                         : phaseProgress < 0.96f ? "3 (Data Exposed)"
                         : "4 (Moment of Choice)";
            Debug.Log($"[Stage5] Phase {phase} | Progress: {phaseProgress:F3}");
        }

        private void OnDestroy()
        {
            AudioListener.volume = _originalVolume;
        }
    }
}
