using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using TheLastCompact.Core;

namespace TheLastCompact.Wakeup
{
    /// <summary>
    /// Stage 5 总控制器 — "Feed / 内容流"
    /// 
    /// 一套系统，三个旋钮。用单个 phaseProgress (0→1) 驱动 A→B→C 三段无缝渐变。
    /// Phase A (0.00~0.35): 解放——多向、随机、惊喜
    /// Phase B (0.35~0.70): 沉迷——单向、过滤、机械
    /// Phase C (0.70~1.00): 恐怖——你的数据成了 feed
    /// 
    /// 职责：
    /// 1. 禁用玩家移动，只保留鼠标旋转（漂浮在虚空中）
    /// 2. 协调 ContentCardSpawner + FeedEnvironment
    /// 3. 注视射线检测 + phaseProgress 推进
    /// 4. Phase C 声音控制（私密数据出现时抽走声音）
    /// 5. 结尾加缪式选择（留下 / 继续）
    /// </summary>
    public class Stage5Controller : MonoBehaviour
    {
        public static Stage5Controller Instance { get; private set; }

        /// <summary>
        /// 自动引导：当 5_Contemporary 场景加载时，自动创建 Stage5Controller。
        /// </summary>
        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void AutoBootstrap()
        {
            SceneManager.sceneLoaded += OnSceneLoaded;
            // 也检查当前场景（编辑器直接Play的情况）
            if (SceneManager.GetActiveScene().name == "5_Contemporary")
            {
                EnsureInstance();
            }
        }

        private static void OnSceneLoaded(UnityEngine.SceneManagement.Scene scene, LoadSceneMode mode)
        {
            if (scene.name == "5_Contemporary")
            {
                EnsureInstance();
            }
        }

        private static void EnsureInstance()
        {
            if (Instance != null) return;
#if UNITY_2023_1_OR_NEWER
            Stage5Controller existing = FindAnyObjectByType<Stage5Controller>();
#else
            Stage5Controller existing = FindObjectOfType<Stage5Controller>();
#endif
            if (existing != null) return;

            GameObject go = new GameObject("Stage5Controller_AutoGenerated");
            go.AddComponent<Stage5Controller>();
            Debug.Log("[Stage5] 自动创建 Stage5Controller。");
        }

        [Header("Phase 进度")]
        [Tooltip("当前阶段进度 0→1，Inspector 中可观测")]
        [Range(0f, 1f)]
        public float phaseProgress = 0f;

        [Tooltip("每次注视交互推进的增量（设大方便快速体验）")]
        public float progressPerGaze = 0.05f;

        [Tooltip("时间自动推进速率（每秒）")]
        public float progressPerSecond = 0.015f;

        [Header("注视检测")]
        [Tooltip("注视射线的最大检测距离")]
        public float gazeRayDistance = 50f;

        [Tooltip("持续注视多久算一次交互（秒）")]
        public float gazeHoldTime = 0.3f;

        [Header("声音控制")]
        [Tooltip("Phase C 私密数据出现时，全局音量降到此值")]
        public float silenceVolume = 0.05f;

        [Header("转场")]
        public float transitionDelay = 2f;
        public string nextSceneName = "6_Future";

        // 子系统引用（运行时自动创建）
        private ContentCardSpawner _spawner;
        private FeedEnvironment _environment;

        // 注视状态
        private ContentCard _currentGazedCard = null;
        private float _gazeTimer = 0f;
        private bool _gazeTriggered = false;

        // 结尾选择
        private bool _endChoiceSpawned = false;
        private bool _isTransitioning = false;

        // 音量控制
        private float _originalVolume = 1f;
        private float _targetVolume = 1f;

        private void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(gameObject); return; }
            Instance = this;
        }

        private void Start()
        {
            // 0. 隐藏场景原有的 UI Canvas（避免旧的数值标签遗留在空天中）
            HideOldCanvases();

            // 1. 压暗环境
            RenderSettings.ambientMode = UnityEngine.Rendering.AmbientMode.Flat;
            RenderSettings.ambientLight = Color.black;
            RenderSettings.skybox = null;

            Camera mainCam = GetMainCamera();
            if (mainCam != null)
            {
                mainCam.clearFlags = CameraClearFlags.SolidColor;
                mainCam.backgroundColor = Color.black;
            }

            // 2. 设置玩家视角只可旋转、移速归零（避免 CharacterController 禁用报错）
            SetupPlayerFloat();

            // 3. 创建注视准心 UI
            CreateReticleUI();

            // 4. 创建子系统
            CreateSubsystems();

            // 5. 保存原始音量
            _originalVolume = AudioListener.volume;

            Debug.Log("[Stage5] Feed 系统已初始化。Phase A 开始。");
        }

        private void HideOldCanvases()
        {
            UnityEngine.Canvas[] canvases = FindObjectsOfType<UnityEngine.Canvas>();
            foreach (var c in canvases)
            {
                if (c.gameObject.name != "ReticleCanvas")
                {
                    c.gameObject.SetActive(false);
                }
            }
        }

        /// <summary>
        /// 创建屏幕中央注视准心（小白点）
        /// </summary>
        private void CreateReticleUI()
        {
            GameObject canvasGo = new GameObject("ReticleCanvas");
            UnityEngine.Canvas canvas = canvasGo.AddComponent<UnityEngine.Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvasGo.AddComponent<UnityEngine.UI.CanvasScaler>();

            GameObject dotGo = new GameObject("ReticleDot");
            dotGo.transform.SetParent(canvasGo.transform, false);
            UnityEngine.UI.Image img = dotGo.AddComponent<UnityEngine.UI.Image>();
            img.color = new Color(1f, 1f, 1f, 0.6f);

            RectTransform rt = dotGo.GetComponent<RectTransform>();
            rt.sizeDelta = new Vector2(6f, 6f);
            rt.anchoredPosition = Vector2.zero;
        }

        private Camera GetMainCamera()
        {
            Camera cam = Camera.main;
            if (cam == null)
            {
#if UNITY_2023_1_OR_NEWER
                cam = FindAnyObjectByType<Camera>();
#else
                cam = FindObjectOfType<Camera>();
#endif
            }
            return cam;
        }

        /// <summary>
        /// 开启玩家控制视角旋转，将移动速度设为 0（避免 Move 报错）
        /// </summary>
        private void SetupPlayerFloat()
        {
#if UNITY_2023_1_OR_NEWER
            UniversalPlayer player = FindAnyObjectByType<UniversalPlayer>();
#else
            UniversalPlayer player = FindObjectOfType<UniversalPlayer>();
#endif
            if (player != null)
            {
                player.moveSpeed = 0f; // 移速归零，无法移动，但允许鼠标转头
                player.EnableControl(); // 开启控制
                Debug.Log("[Stage5] 玩家移速已设为 0，视角旋转已启用。");
            }

            // 锁定鼠标
            CursorService.Lock();
        }

        private void Update()
        {
            // 快捷键调试：按数字键 1~5 直接切到对应 Phase
            if (Input.GetKeyDown(KeyCode.Alpha1) || Input.GetKeyDown(KeyCode.Keypad1))
            {
                phaseProgress = 0.05f;
                Debug.Log("<color=green>[Stage5 调试] 已快捷跳转至 Phase A (解放 - 随机感官)</color>");
            }
            else if (Input.GetKeyDown(KeyCode.Alpha2) || Input.GetKeyDown(KeyCode.Keypad2))
            {
                phaseProgress = 0.40f;
                Debug.Log("<color=yellow>[Stage5 调试] 已快捷跳转至 Phase B (沉迷 - 偏好过滤/隧道)</color>");
            }
            else if (Input.GetKeyDown(KeyCode.Alpha3) || Input.GetKeyDown(KeyCode.Keypad3))
            {
                phaseProgress = 0.75f;
                Debug.Log("<color=orange>[Stage5 调试] 已快捷跳转至 Phase C 步骤一 (高科技算法诊断)</color>");
            }
            else if (Input.GetKeyDown(KeyCode.Alpha4) || Input.GetKeyDown(KeyCode.Keypad4))
            {
                phaseProgress = 0.92f;
                Debug.Log("<color=red>[Stage5 调试] 已快捷跳转至 Phase C 步骤三 (私密数据核爆/静音)</color>");
            }
            else if (Input.GetKeyDown(KeyCode.Alpha5) || Input.GetKeyDown(KeyCode.Keypad5))
            {
                phaseProgress = 0.98f;
                Debug.Log("<color=cyan>[Stage5 调试] 已快捷跳转至 结尾加缪式选择卡片</color>");
            }

            // 自动推进 phaseProgress
            if (phaseProgress < 1f)
            {
                phaseProgress += progressPerSecond * Time.deltaTime;
                phaseProgress = Mathf.Clamp01(phaseProgress);
            }

            // 同步旋钮给子系统
            if (_spawner != null) _spawner.phaseProgress = phaseProgress;
            if (_environment != null) _environment.phaseProgress = phaseProgress;

            // 注视射线检测
            ProcessGaze();

            // 音量平滑过渡
            AudioListener.volume = Mathf.Lerp(AudioListener.volume, _targetVolume, Time.deltaTime * 3f);

            // 结尾选择
            if (phaseProgress >= 0.98f && !_endChoiceSpawned)
            {
                SpawnEndChoice();
            }

            // P 键调试跳关
            if (Input.GetKeyDown(KeyCode.P) && !_isTransitioning)
            {
                StartCoroutine(TransitionSequence());
            }
        }

        private void CreateSubsystems()
        {
            // ContentCardSpawner
            GameObject spawnerGo = new GameObject("ContentCardSpawner");
            spawnerGo.transform.SetParent(transform, false);
            _spawner = spawnerGo.AddComponent<ContentCardSpawner>();
            _spawner.OnCardSpawned += OnCardSpawned;

            // FeedEnvironment
            GameObject envGo = new GameObject("FeedEnvironment");
            envGo.transform.SetParent(transform, false);
            _environment = envGo.AddComponent<FeedEnvironment>();
        }

        private void OnCardSpawned(ContentCard card)
        {
            // 注册选择回调
            card.OnChoiceSelected += OnChoiceSelected;
        }

        /// <summary>
        /// 注视射线检测：摄像机中心射线命中卡片
        /// </summary>
        private void ProcessGaze()
        {
            Camera cam = Camera.main;
            if (cam == null) return;

            Ray ray = new Ray(cam.transform.position, cam.transform.forward);
            RaycastHit hit;

            if (Physics.Raycast(ray, out hit, gazeRayDistance))
            {
                ContentCard card = hit.collider.GetComponent<ContentCard>();
                if (card != null)
                {
                    if (_currentGazedCard != card)
                    {
                        // 新卡片
                        if (_currentGazedCard != null) _currentGazedCard.OnGazeExit();
                        _currentGazedCard = card;
                        _gazeTimer = 0f;
                        _gazeTriggered = false;
                    }

                    _gazeTimer += Time.deltaTime;

                    if (_gazeTimer >= gazeHoldTime && !_gazeTriggered)
                    {
                        _gazeTriggered = true;
                        card.OnGazeEnter();

                        // 推进 phaseProgress
                        phaseProgress += progressPerGaze;
                        phaseProgress = Mathf.Clamp01(phaseProgress);

                        // 声音控制
                        if (card.isPrivateDataCard)
                        {
                            // 私密数据：抽走声音
                            _targetVolume = silenceVolume;
                        }
                        else
                        {
                            // 正常：恢复音量
                            _targetVolume = _originalVolume;
                        }

                        LogPhase();
                    }

                    return;
                }
            }

            // 没命中任何卡片
            if (_currentGazedCard != null)
            {
                _currentGazedCard.OnGazeExit();
                _currentGazedCard = null;
                _gazeTimer = 0f;
                _gazeTriggered = false;
            }

            // 没注视私密卡时逐步恢复音量
            _targetVolume = _originalVolume;
        }

        /// <summary>
        /// 生成结尾加缪式选择卡片
        /// </summary>
        private void SpawnEndChoice()
        {
            _endChoiceSpawned = true;
            Debug.Log("[Stage5] Phase C 完成。生成加缪式选择。");

            Camera cam = Camera.main;
            Vector3 fwd = cam.transform.forward;
            Vector3 right = cam.transform.right;

            // "留在这里" 卡片（左侧）
            SpawnChoiceCard(
                cam.transform.position + fwd * 8f - right * 3f,
                "Stay here.\nIn this beautiful place.",
                "stay",
                new Color(0.9f, 0.95f, 1f, 0.95f)
            );

            // "继续" 卡片（右侧）
            SpawnChoiceCard(
                cam.transform.position + fwd * 8f + right * 3f,
                "Continue.\nThere is still a door.",
                "continue",
                new Color(1f, 0.95f, 0.9f, 0.95f)
            );
        }

        private void SpawnChoiceCard(Vector3 pos, string text, string action, Color color)
        {
            GameObject cardGo = GameObject.CreatePrimitive(PrimitiveType.Quad);
            cardGo.name = $"ChoiceCard_{action}";
            cardGo.transform.position = pos;
            cardGo.transform.localScale = Vector3.one * 2.5f;

            Collider col = cardGo.GetComponent<Collider>();
            if (col != null) Destroy(col);
            BoxCollider box = cardGo.AddComponent<BoxCollider>();
            box.isTrigger = true;

            Renderer rend = cardGo.GetComponent<Renderer>();
            Material mat = new Material(Shader.Find("Universal Render Pipeline/Unlit"));
            mat.SetFloat("_Surface", 1);
            mat.SetInt("_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha);
            mat.SetInt("_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);
            mat.SetInt("_ZWrite", 0);
            mat.renderQueue = 3000;
            rend.material = mat;

            ContentCard card = cardGo.AddComponent<ContentCard>();
            card.cardText = text;
            card.cardColor = color;
            card.isChoiceCard = true;
            card.choiceAction = action;
            card.driftSpeed = 0.3f; // 缓慢漂
            card.gazeAttractSpeed = 2f;
            card.maxLifetime = 999f;
            card.OnChoiceSelected += OnChoiceSelected;
        }

        private void OnChoiceSelected(string action)
        {
            if (_isTransitioning) return;

            if (action == "continue")
            {
                Debug.Log("[Stage5] 玩家选择继续。转场至 6_Future。");
                StartCoroutine(TransitionSequence());
            }
            else if (action == "stay")
            {
                Debug.Log("[Stage5] 玩家选择留下。Feed 永远继续。");
                // Feed 继续无限循环，不转场
                // 重置 phaseProgress 到 Phase A 让循环重新开始
                phaseProgress = 0f;
                _endChoiceSpawned = false;
            }
        }

        private IEnumerator TransitionSequence()
        {
            _isTransitioning = true;
            EventBus.RaiseAnnouncement("The feed never ends. But you chose to look away.");
            yield return new WaitForSeconds(transitionDelay);
            PerformSceneTransition();
        }

        private void PerformSceneTransition()
        {
            // 恢复音量
            AudioListener.volume = _originalVolume;

            EventBus.RaiseSceneComplete();

#if UNITY_EDITOR
            if (FindAnyObjectByType<SceneTransitionManager>() == null)
            {
                Debug.LogWarning($"[Stage5] 未检测到 SceneTransitionManager，单关测试模式：直接加载 {nextSceneName}");
                SceneManager.LoadScene(nextSceneName);
            }
#endif
        }

        private void LogPhase()
        {
            string phase = phaseProgress < 0.35f ? "A (解放)"
                         : phaseProgress < 0.70f ? "B (沉迷)"
                         : "C (恐怖)";
            Debug.Log($"[Stage5] Phase {phase} | Progress: {phaseProgress:F3}");
        }

        private void OnDestroy()
        {
            AudioListener.volume = _originalVolume;
        }
    }
}
