using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using TheLastCompact.Core;

namespace TheLastCompact.Wakeup
{
    /// <summary>
    /// 第 6 阶段（6_Future / 未来关卡）总控制器。
    /// 包含：BGM 背景音乐自动挂载、旧旁白关闭、Inspector 拖入音轨接口。
    /// </summary>
    public class Stage6Controller : MonoBehaviour
    {
        public static Stage6Controller Instance { get; private set; }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
        private static void AutoBootstrap()
        {
            SceneManager.sceneLoaded += OnSceneLoaded;
            if (SceneManager.GetActiveScene().name == "6_Future")
            {
                EnsureInstance();
            }
        }

        private static void OnSceneLoaded(Scene scene, LoadSceneMode mode)
        {
            if (scene.name == "6_Future")
            {
                EnsureInstance();
            }
        }

        private static void EnsureInstance()
        {
            if (Instance != null) return;
#if UNITY_2023_1_OR_NEWER
            Stage6Controller existing = FindAnyObjectByType<Stage6Controller>();
#else
            Stage6Controller existing = FindObjectOfType<Stage6Controller>();
#endif
            if (existing != null) return;

            GameObject go = new GameObject("Stage6Controller_AutoGenerated");
            go.AddComponent<Stage6Controller>();
            Debug.Log("[Stage6] 自动创建 Stage6Controller。");
        }

        [Header("BGM 背景音乐")]
        [Tooltip("Stage 6 背景音乐 AudioClip（在 Inspector 中拖入音轨）")]
        public AudioClip bgmClip;

        [Tooltip("BGM 音量 (0 ~ 1)")]
        [Range(0f, 1f)]
        public float bgmVolume = 0.5f;

        [Tooltip("是否循环播放 BGM")]
        public bool loopBgm = true;

        private AudioSource _bgmAudioSource;

        private void Awake()
        {
            if (Instance != null && Instance != this)
            {
                Destroy(gameObject);
                return;
            }
            Instance = this;
        }

        private void Start()
        {
            // 0. 彻底关掉之前关卡残留的旁白/对话系统
            if (NarratorManager.Instance != null)
            {
                NarratorManager.Instance.StopCurrent();
                NarratorManager.Instance.gameObject.SetActive(false);
                Debug.Log("[Stage6] 已关闭之前的旁白对话系统 (NarratorManager)。");
            }

            // 1. 配置并播放 BGM
            SetupBGM();

            Debug.Log("[Stage6] Stage 6 核心控制器初始化就绪。");
        }

        private void SetupBGM()
        {
            _bgmAudioSource = gameObject.AddComponent<AudioSource>();
            _bgmAudioSource.loop = loopBgm;
            _bgmAudioSource.volume = bgmVolume;
            _bgmAudioSource.spatialBlend = 0f; // 2D 环绕背景音

            if (bgmClip != null)
            {
                _bgmAudioSource.clip = bgmClip;
                _bgmAudioSource.Play();
                Debug.Log($"[Stage6] 播放指定的 BGM: {bgmClip.name}");
            }
        }
    }
}
